import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/navbar.js';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MGM NUTRICION ANIMAL",
  keywords: ["nextjs", "geist", "react", "javascript"],
  authors: [
    {
      name: "David Martinez",
      url: "https://github.com/lobodecm",
    },
  ],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar className="sticky top-0 z-50 bg-black"/>
        <main>{children}</main>
        {children}
      </body>
    </html>
  );
}